Enable mdbook-linkcheck in CI
Now that mdbook-linkcheck can run without warnings, it is no longer
marked as optional in the book.toml configuration and it is installed
in the CI workflow, so it can run like the other mdbook tools.

A broken link will fail CI, with a clear error message about which
link is broken and where it is located:

  ```
  2026-03-12 15:15:06 [INFO] (mdbook::book): Running the linkcheck
    backend
  2026-03-12 15:15:06 [INFO] (mdbook::renderer): Invoking the
    "linkcheck" renderer
  error: File not found: intentional_broken_link.md
    ┌─ community/communications/contact_us.md:8:1
    │
  8 │ [Mailing-Lists](intentional_broken_link.md) list.
    │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |        File not found: intentional_broken_link.md

  Error: One or more incorrect links
  ```

Signed-off-by: Michael Kubacki <michael.kubacki@microsoft.com>